# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:


  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
  #
  - trigger: ":BR"
    replace: "Best Regards\n\n{{myname}}"

  - trigger: ":thx"
    replace: "Thanks,\n\n{{myname}}"

  - trigger: ":mfg"
    replace: "Viele GrÃ¼ÃŸe\n\n{{myname}}"

  - trigger: "hallo *"
    replace: "Hallo Zusammen,\n\n"

  
  - trigger: "gitcfg"
    replace: |
              git config user.name "{{myname}} {{mylastname}}"
              git config user.email "{{myname}}.{{mylastname}}@raith.de"

  - trigger: ":facepalm"
    replace: "ðŸ¤¦"

  - trigger: "mygmail"
    replace: "{{lowercase}}"
    vars:
      - name: lowercase
        type: shell
        params: 
          cmd: "echo $ESPANSO_MYNAME.$ESPANSO_MYLASTNAME@gmail.com"

  - trigger: ":phone"
    replace: "+491797715371"
  
  - trigger: 'Im'
    replace: 'Im'
    propagate_case: false
    word: true

  - regex: "dtw\\d{4}-\\d{2}(-\\d{2})?\\."
    replace: "Bingo!"

  - trigger: "eline"
    replace: "eLiNE"

  - trigger: ":ptb"
    replace: "`process trigger box`"

  - trigger: ":todo"
    replace: "TODO "
